vich_uploader:
    db_driver: orm

    mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

        ad:
            uri_prefix: /upload/image
            upload_destination: "%kernel.project_dir%/public/upload/image"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            # directory_namer: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
            # directory_namer: directory_namer.user

            inject_on_load: true
            delete_on_update: false
            delete_on_remove: true